pipeline {
    environment {
        registry = "hackcoderr/crud-app:latest" 
        registryCredential = 'docker-cred'
        dockerImage = ''
    }
    agent{
        label 'docker-swarm-node-1'
    }

    stages {
        stage('SCM') {
            steps {
                git 'https://github.com/hackcoderr/jenkins-test.git'
            }
        }
        stage('Build image') { 
            steps { 
                script { 
                    dockerImage = docker.build registry  
                }
            } 
        }
        stage('Deploy image') { 
            steps { 
                script { 
                    docker.withRegistry( '', registryCredential ) { 
                        dockerImage.push() 
                    }
                } 
            }
        }
        stage('Docker stack') {
            steps {
                sh 'docker stack deploy -c crud-stack.yaml crud-app'
            }
        }
    }
}

